# Generated by Django 4.1.1 on 2022-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Digital', 'DIGITAL'), ('Physical', 'PHYSICAL')], default='DIGITAL', max_length=20),
        ),
    ]
